import type { ProviderApiFormat, ProviderKind } from '@malang/shared'

export type ProviderMeta = {
    id: ProviderKind
    label: string
    auth: 'none' | 'key' | 'optionalKey' | 'vertex' | 'aws' | 'unsupported'
    model: string
    baseUrl?: string
    description: string
    formats?: ProviderApiFormat[]
}

export const providers: ProviderMeta[] = [
    {
        id: 'openai',
        label: 'OpenAI',
        auth: 'key',
        model: 'gpt-5-mini',
        baseUrl: 'https://api.openai.com/v1',
        description: 'Chat Completions 및 Responses API',
        formats: ['openai-chat', 'openai-responses'],
    },
    {
        id: 'openrouter',
        label: 'OpenRouter',
        auth: 'key',
        model: 'openrouter/auto',
        baseUrl: 'https://openrouter.ai/api/v1',
        description: 'Provider routing, fallback 및 middle-out 옵션 지원',
        formats: ['openai-chat'],
    },
    {
        id: 'anthropic',
        label: 'Anthropic',
        auth: 'key',
        model: 'claude-sonnet-4-5',
        baseUrl: 'https://api.anthropic.com/v1',
        description: 'Claude Messages API',
    },
    {
        id: 'google',
        label: 'Google AI Studio',
        auth: 'key',
        model: 'gemini-2.5-flash',
        description: 'Gemini Developer API',
    },
    {
        id: 'vertex',
        label: 'Vertex AI',
        auth: 'vertex',
        model: 'gemini-2.5-flash',
        description: 'API key, 서비스 계정 또는 ADC',
    },
    {
        id: 'mistral',
        label: 'Mistral AI',
        auth: 'key',
        model: 'mistral-large-latest',
        baseUrl: 'https://api.mistral.ai/v1',
        description: 'Mistral OpenAI-compatible API',
    },
    {
        id: 'deepseek',
        label: 'DeepSeek',
        auth: 'key',
        model: 'deepseek-chat',
        baseUrl: 'https://api.deepseek.com',
        description: 'DeepSeek chat/reasoner API',
    },
    {
        id: 'deepinfra',
        label: 'DeepInfra',
        auth: 'key',
        model: 'deepseek-ai/DeepSeek-V3',
        baseUrl: 'https://api.deepinfra.com/v1/openai',
        description: 'DeepInfra OpenAI-compatible API',
    },
    {
        id: 'cohere',
        label: 'Cohere',
        auth: 'key',
        model: 'command-r-plus',
        baseUrl: 'https://api.cohere.com',
        description: 'Cohere Chat API',
    },
    {
        id: 'aws',
        label: 'AWS Bedrock',
        auth: 'aws',
        model: 'anthropic.claude-sonnet-4-5-20250929-v1:0',
        description: 'Bedrock Converse Stream',
    },
    {
        id: 'novelai',
        label: 'NovelAI',
        auth: 'key',
        model: 'kayra-v1',
        baseUrl: 'https://text.novelai.net/ai/generate',
        description: 'NovelAI text generation',
    },
    {
        id: 'novellist',
        label: 'NovelList',
        auth: 'key',
        model: 'damsel',
        baseUrl: 'https://api.tringpt.com/api',
        description: 'NovelList wire format',
    },
    {
        id: 'horde',
        label: 'AI Horde',
        auth: 'optionalKey',
        model: 'auto',
        baseUrl: 'https://stablehorde.net/api/v2',
        description: '익명 키 또는 Horde API key',
    },
    {
        id: 'nanogpt',
        label: 'NanoGPT',
        auth: 'key',
        model: 'openai/gpt-5-mini',
        baseUrl: 'https://nano-gpt.com/api/v1',
        description: 'NanoGPT chat/responses/messages 호환',
        formats: ['openai-chat', 'openai-responses', 'anthropic-messages'],
    },
    {
        id: 'openai-compatible',
        label: 'OpenAI Compatible',
        auth: 'optionalKey',
        model: 'model',
        description: 'OpenRouter, Together, Groq, LM Studio 및 reverse proxy',
        formats: ['openai-chat', 'openai-responses', 'anthropic-messages'],
    },
    {
        id: 'ooba',
        label: 'Ooba / Text Generation WebUI',
        auth: 'optionalKey',
        model: 'model',
        baseUrl: 'http://127.0.0.1:5000/v1',
        description: 'Ooba /v1/completions 및 OpenAI chat endpoint',
        formats: ['openai-completions', 'openai-chat'],
    },
    {
        id: 'mancer',
        label: 'Mancer / Ooba Legacy',
        auth: 'key',
        model: 'mancer',
        description: 'Ooba Legacy /api/v1/generate 규격',
    },
    {
        id: 'kobold',
        label: 'KoboldAI',
        auth: 'none',
        model: 'kobold',
        baseUrl: 'http://127.0.0.1:5001',
        description: 'Kobold /api/v1/generate',
    },
    {
        id: 'ollama',
        label: 'Ollama',
        auth: 'none',
        model: 'qwen3:latest',
        baseUrl: 'http://127.0.0.1:11434',
        description: 'Ollama native chat API',
    },
    {
        id: 'echo',
        label: 'Echo (개발용)',
        auth: 'none',
        model: 'echo',
        description: '네트워크 없이 고정 응답 반환',
    },
    {
        id: 'webllm',
        label: 'WebLLM',
        auth: 'unsupported',
        model: 'webllm',
        description: '브라우저 GPU 전용 — 서버에서는 명시적 오류',
    },
    {
        id: 'plugin',
        label: '브라우저 플러그인',
        auth: 'unsupported',
        model: 'plugin',
        description: '브라우저 플러그인 전용 — endpoint 변환 필요',
    },
]
