export function v3Card(overrides: Record<string, unknown> = {}) {
    return {
        spec: 'chara_card_v3',
        spec_version: '3.0',
        data: {
            name: 'Aria',
            description: 'An archivist.',
            personality: 'Curious',
            scenario: 'A quiet library',
            first_mes: 'Welcome, {{user}}.',
            mes_example: '',
            creator_notes: '',
            system_prompt: '',
            post_history_instructions: '',
            alternate_greetings: ['You came back.'],
            group_only_greetings: [],
            tags: ['test'],
            creator: 'Malang',
            character_version: '1.0',
            extensions: { malang_test: true },
            character_book: {
                name: 'Library',
                description: '',
                scan_depth: 5,
                token_budget: 500,
                recursive_scanning: true,
                extensions: {},
                entries: [
                    {
                        keys: ['moon'],
                        secondary_keys: [],
                        content: 'The moon archive is restricted.',
                        enabled: true,
                        insertion_order: 0,
                        case_sensitive: false,
                        use_regex: false,
                        constant: false,
                        selective: false,
                        priority: 10,
                        name: 'Moon archive',
                        comment: '',
                        extensions: {},
                    },
                ],
            },
            ...overrides,
        },
    }
}
