/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceModulesRouteImport } from './routes/_workspace/modules'
import { Route as WorkspacePromptsRouteImport } from './routes/_workspace/prompts'
import { Route as WorkspaceCharactersIndexRouteImport } from './routes/_workspace/characters/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceSettingsSectionRouteImport } from './routes/_workspace/settings/$section'
import { Route as WorkspaceCharactersCharacterIdIndexRouteImport } from './routes/_workspace/characters/$characterId/index'
import { Route as WorkspaceCharactersCharacterIdCharacterSectionRouteImport } from './routes/_workspace/characters/$characterId/character/$section'
import { Route as WorkspaceCharactersCharacterIdChatsConversationIdRouteImport } from './routes/_workspace/characters/$characterId/chats/$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceModulesRoute = WorkspaceModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePromptsRoute = WorkspacePromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCharactersIndexRoute =
  WorkspaceCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsSectionRoute =
  WorkspaceSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCharactersCharacterIdIndexRoute =
  WorkspaceCharactersCharacterIdIndexRouteImport.update({
    id: '/characters/$characterId/',
    path: '/characters/$characterId/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCharactersCharacterIdCharacterSectionRoute =
  WorkspaceCharactersCharacterIdCharacterSectionRouteImport.update({
    id: '/characters/$characterId/character/$section',
    path: '/characters/$characterId/character/$section',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCharactersCharacterIdChatsConversationIdRoute =
  WorkspaceCharactersCharacterIdChatsConversationIdRouteImport.update({
    id: '/characters/$characterId/chats/$conversationId',
    path: '/characters/$characterId/chats/$conversationId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/modules': typeof WorkspaceModulesRoute
  '/prompts': typeof WorkspacePromptsRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/characters/': typeof WorkspaceCharactersIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/characters/$characterId/': typeof WorkspaceCharactersCharacterIdIndexRoute
  '/characters/$characterId/character/$section': typeof WorkspaceCharactersCharacterIdCharacterSectionRoute
  '/characters/$characterId/chats/$conversationId': typeof WorkspaceCharactersCharacterIdChatsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/modules': typeof WorkspaceModulesRoute
  '/prompts': typeof WorkspacePromptsRoute
  '/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/characters': typeof WorkspaceCharactersIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/characters/$characterId': typeof WorkspaceCharactersCharacterIdIndexRoute
  '/characters/$characterId/character/$section': typeof WorkspaceCharactersCharacterIdCharacterSectionRoute
  '/characters/$characterId/chats/$conversationId': typeof WorkspaceCharactersCharacterIdChatsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/modules': typeof WorkspaceModulesRoute
  '/_workspace/prompts': typeof WorkspacePromptsRoute
  '/_workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/_workspace/characters/': typeof WorkspaceCharactersIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/_workspace/characters/$characterId/': typeof WorkspaceCharactersCharacterIdIndexRoute
  '/_workspace/characters/$characterId/character/$section': typeof WorkspaceCharactersCharacterIdCharacterSectionRoute
  '/_workspace/characters/$characterId/chats/$conversationId': typeof WorkspaceCharactersCharacterIdChatsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/modules'
    | '/prompts'
    | '/settings/$section'
    | '/characters/'
    | '/settings/'
    | '/characters/$characterId/'
    | '/characters/$characterId/character/$section'
    | '/characters/$characterId/chats/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/modules'
    | '/prompts'
    | '/settings/$section'
    | '/characters'
    | '/settings'
    | '/characters/$characterId'
    | '/characters/$characterId/character/$section'
    | '/characters/$characterId/chats/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/modules'
    | '/_workspace/prompts'
    | '/_workspace/settings/$section'
    | '/_workspace/characters/'
    | '/_workspace/settings/'
    | '/_workspace/characters/$characterId/'
    | '/_workspace/characters/$characterId/character/$section'
    | '/_workspace/characters/$characterId/chats/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/modules': {
      id: '/_workspace/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof WorkspaceModulesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/prompts': {
      id: '/_workspace/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof WorkspacePromptsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/characters/': {
      id: '/_workspace/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof WorkspaceCharactersIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/$section': {
      id: '/_workspace/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof WorkspaceSettingsSectionRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/characters/$characterId/': {
      id: '/_workspace/characters/$characterId/'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId/'
      preLoaderRoute: typeof WorkspaceCharactersCharacterIdIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/characters/$characterId/character/$section': {
      id: '/_workspace/characters/$characterId/character/$section'
      path: '/characters/$characterId/character/$section'
      fullPath: '/characters/$characterId/character/$section'
      preLoaderRoute: typeof WorkspaceCharactersCharacterIdCharacterSectionRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/characters/$characterId/chats/$conversationId': {
      id: '/_workspace/characters/$characterId/chats/$conversationId'
      path: '/characters/$characterId/chats/$conversationId'
      fullPath: '/characters/$characterId/chats/$conversationId'
      preLoaderRoute: typeof WorkspaceCharactersCharacterIdChatsConversationIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceModulesRoute: typeof WorkspaceModulesRoute
  WorkspacePromptsRoute: typeof WorkspacePromptsRoute
  WorkspaceSettingsSectionRoute: typeof WorkspaceSettingsSectionRoute
  WorkspaceCharactersIndexRoute: typeof WorkspaceCharactersIndexRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
  WorkspaceCharactersCharacterIdIndexRoute: typeof WorkspaceCharactersCharacterIdIndexRoute
  WorkspaceCharactersCharacterIdCharacterSectionRoute: typeof WorkspaceCharactersCharacterIdCharacterSectionRoute
  WorkspaceCharactersCharacterIdChatsConversationIdRoute: typeof WorkspaceCharactersCharacterIdChatsConversationIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceModulesRoute: WorkspaceModulesRoute,
  WorkspacePromptsRoute: WorkspacePromptsRoute,
  WorkspaceSettingsSectionRoute: WorkspaceSettingsSectionRoute,
  WorkspaceCharactersIndexRoute: WorkspaceCharactersIndexRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  WorkspaceCharactersCharacterIdIndexRoute:
    WorkspaceCharactersCharacterIdIndexRoute,
  WorkspaceCharactersCharacterIdCharacterSectionRoute:
    WorkspaceCharactersCharacterIdCharacterSectionRoute,
  WorkspaceCharactersCharacterIdChatsConversationIdRoute:
    WorkspaceCharactersCharacterIdChatsConversationIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
